Update

diff --git a/bin/task/run b/bin/task/run
--- a/bin/task/run
+++ b/bin/task/run
@@ -2,65 +2,50 @@
 # Runs specific tasks.
 # Assumes bin/setup has been run.
 
-print_help () {
-  echo "Runs specific tasks."
-  echo "Usage: $0 <mode> <task> [<args...>]"
-  echo "Modes:"
-  echo " $0 local <task>:   runs tasks entirely on current machine"
-  echo " $0 remote <task>:  queues tasks to execute on deployed infra via RabbitMQ"
-  echo " $0 help:           prints this help (default)"
-  echo "Tasks:"
-  echo " $0 <mode> units:      runs DM on all units"
-  echo " $0 <mode> community:  runs DM for a given community"
+# Fail on invalid variable references
+set -u
+
+print_help() {
+  cat <<HELP
+Runs specific tasks.
+Usage: $0 <mode> <task> [<args...>]
+  $0 local <task>:   runs tasks entirely on current machine
+  $0 remote <task>:  queues tasks to execute on deployed infra via RabbitMQ
+  $0 help:           prints this help (default)
+HELP
 }
 
-celery_app="app.task.registry"
+cmd="${1:-help}"
 
-mode="${1:-help}"
-
-if [[ "$mode" == "help" || "$mode" == "--help" || "$mode" == "-h" ]]; then
+if [[ "$cmd" == "help" || "$cmd" == "--help" || "$cmd" == "-h" ]]; then
   print_help
   exit 0
-elif [[ "$mode" == "local" ]]; then
+elif [[ "$cmd" == "local" ]]; then
   celery_local="true"
-elif [[ "$mode" == "remote" ]]; then
+elif [[ "$cmd" == "remote" ]]; then
   celery_local="false"
 else
-  echo "Unrecognized mode <$1>."
+  echo "Unrecognized task runner subcommand: <$cmd>."
   print_help
   exit 1
 fi
 
-name="${2}"
+task="${2}"
 
-if [[ "$name" == "new_year" ]]; then
-  celery_task_module="app.tasks.recurring"
-  celery_task_name="ring_in_the_new_year"
-else
-  echo "Unrecognized task <$2>."
-  print_help
-  exit 1
-fi
+celery_task_module=${task%.*}
+celery_task_name=${task##*.}
 
-args=${@:3}
+declare -a args
+args=("${@:3}")
+
+# Ensure failures propegate
+set -e
 
 # Echo commands
 set -x
 
 # Inexplicably, `celery call` ignores always-eager settings, so we implement task calling ourselves
-CELERY_TASK_ALWAYS_EAGER=$celery_local python - <<-"EOF" $celery_task_module $celery_task_name $args
-import sys
-from importlib import import_module
-
-if __name__ == "__main__":
-    module_name = sys.argv[1]
-    function_name = sys.argv[2]
-    args = sys.argv[3:]
-
-    module = import_module(module_name)
-    function = module.__getattribute__(function_name)
-    if callable(function) and 'apply_async' in dir(function):
-        function.apply_async(args=args)
-    else:
-        raise "Celery task not provided."
-EOF
+CELERY_TASK_ALWAYS_EAGER="$celery_local" python scripts/task/runner.py \
+  "$celery_task_module" \
+  "$celery_task_name" \
+  "${args[@]}"
